version: '2'
services:
    redditlite-app:
        image: redditlite
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://redditlite-mysql:3306/redditlite?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    redditlite-mysql:
        extends:
            file: mysql.yml
            service: redditlite-mysql
